<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Domolas</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.2/css/bootstrap-combined.min.css" rel="stylesheet">
    <link href="<?php echo $this->asset('assets/css/layout.css') ?>" rel="stylesheet">
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.2/js/bootstrap.min.js"></script>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <?php if ($this['atomik.debug'] && Atomik::isPluginLoaded('DebugBar')) echo $this->renderDebugBarHead(); ?>
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="#">Domolas</a>
          <ul class="nav">
            <li class="active"><a href="#">Home</a></li>
            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Action</a></li>
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something else here</a></li>
                                    <li class="divider"></li>
                                    <li class="nav-header">Nav header</li>
                                    <li><a href="#">Separated link</a></li>
                                    <li><a href="#">One more separated link</a></li>
                                </ul>
                            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="container-fluid">
      <?php if (count($this['flash_messages'])): ?>
        <?php foreach ($this['flash_messages'] as $label => $messages): ?>
          <?php foreach ($messages as $message): ?>
            <div class="alert alert-<?php echo $label ?>"><?php echo $message ?></li>
          <?php endforeach; ?>
        <?php endforeach; ?>
      <?php endif ?>
    
      <div id="content">
        <?php echo $contentForLayout; ?>
      </div>
    </div>
    <?php if ($this['atomik.debug'] && Atomik::isPluginLoaded('DebugBar')) echo $this->renderDebugBar(); ?>
  </body>
</html>
